// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvsexzopuvnrpuhaftvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2c2V4em9wdXZucnB1aGFmdHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTQyNzEsImV4cCI6MjA3MjczMDI3MX0.hyIIZo0nXfeviZ64BAicpVOlogxrlVdkmO4aMXVq7iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});