// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrywjbxqlqpdzrudfupm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyeXdqYnhxbHFwZHpydWRmdXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjM0MTMsImV4cCI6MjA2MzYzOTQxM30.tHBkiztnuUhjLLwq1zraM0XpG1MvLPON40m3jdNIEkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});